project_id = "study-ai"

[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 55322
shadow_port = 55320
major_version = 17

[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = false

[storage]
enabled = true
file_size_limit = "50MiB"

[local_smtp]
enabled = true
port = 55324
smtp_port = 55325
pop3_port = 55326

[analytics]
enabled = true
port = 55327
backend = "postgres"

[edge_runtime]
enabled = false

[db.pooler]
enabled = false
