import { expect, test } from "@playwright/test";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
const vaultDir=path.join(process.cwd(),"e2e","fixtures","vault"),schedulePath=path.join(vaultDir,"schedule.md"),plansDir=path.join(vaultDir,"plans");
const SCHEDULE_FIXTURE=["---","type: schedule","schema_version: 1","updated: 2026-07-24T22:10:00+09:00","---","","## 予定","- [ ] id=ev-1 | kind=mock_exam | title=第2回模試 | due=2026-08-01","- [x] id=ev-2 | kind=assignment | title=英語課題 | due=2026-07-20",""].join("\n");
const today=new Date(),todayKey=`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,"0")}-${String(today.getDate()).padStart(2,"0")}`,todayPlanPath=path.join(plansDir,`${todayKey}.md`),TODAY_PLAN=["---","type: study-plan",`date: ${todayKey}`,"schema_version: 1","---","","## 計画","- id=p-1 | start=09:00 | end=10:30 | subject=英語R | status=planned | memo=E2E計画",""].join("\n");
test.beforeEach(async()=>{await writeFile(schedulePath,SCHEDULE_FIXTURE);await mkdir(plansDir,{recursive:true});await writeFile(todayPlanPath,TODAY_PLAN)}); test.afterEach(async()=>{await writeFile(schedulePath,SCHEDULE_FIXTURE);await rm(todayPlanPath,{force:true})});
test("/scheduleで予定一覧と当日の学習計画が表示される",async({page})=>{await page.goto("/schedule");await expect(page.getByText("第2回模試")).toBeVisible();await expect(page.getByText("英語課題")).toBeVisible();await expect(page.getByText("E2E計画")).toBeVisible()});
test("予定の完了チェックボックスをタップするとschedule.mdが書き換わる",async({page})=>{await page.goto("/schedule");await page.getByRole("checkbox",{name:"第2回模試を完了にする"}).click();await expect(async()=>expect(await readFile(schedulePath,"utf8")).toContain("- [x] id=ev-1 | kind=mock_exam | title=第2回模試 | due=2026-08-01")).toPass()});
test("週の学習時間を保存できる",async({page})=>{await page.goto("/stats");await page.getByLabel("週合計（分）").fill("345");await page.getByRole("button",{name:"保存"}).first().click();await expect(page.getByText("週次振り返り・来週の重点")).toBeVisible()});
